# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-managed-prometheus-workspace
  description: This component is responsible for provisioning a workspace for Amazon Managed Service for Prometheus, also known as Amazon Managed Prometheus (AMP)
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component








